spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers

offer:
  http:
    client:
      config:
        connectionTimeout: 5000
        readTimeout: 5000
        port: 5057
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        service: offers
