spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      auto-index-creation: true
#      uri: mongodb://admin:admin@localhost:27017/offers
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offer:
  http:
    client:
      config:
        connectionTimeout: 5000
        readTimeout: 5000
        port: 5057
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        service: offers
  scheduler:
    request:
      delay: PT3H
    config:
      enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend